name: "Jenkins-Action with Test Data"
description: "Start Jenkins jobs and report back url, status of build, and any test results"
author: "Cameron Myers"
inputs:
  gh_token:
    description: "Github Token"
    required: true
  url:
    description: "Jenkins URL including http protocol"
    required: true
  job_name:
    description: "Jenkins job name to build"
    required: true
  username:
    description: "Jenkins username"
    required: false
  api_token:
    description: "Jenkins API token"
    required: false
  parameters:
    description: 'Build parameters in JSON format e.g. `{"field1": "value1"}`'
    required: false
  cookies:
    description: 'Cookies to include in HTTP requests in JSON format e.g. `{"field1":"value1"}`'
    required: false
  wait:
    description: "Should the runner wait for the build to finish and provide ok status"
    required: false
    default: "True"
  timeout:
    description: "Timeout in seconds for build to complete"
    required: false
    default: "600"
  start_timeout:
    description: "Timeout in seconds for build to start"
    required: false
    default: "600"
  interval:
    description: "How frequently in seconds to query Jenkins for build status"
    required: false
    default: "5"
outputs:
  build_url:
    description: "Jenkins build URL"
  test_results:
    description: "JUnit Test results from Jenkins Build"
runs:
  using: "docker"
  image: "Dockerfile"
